---
name: Deploy Infrastructure
run-name: ${{ github.actor }} is deploying infrastructure
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
env:
  env_name: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
jobs:
  deploy-bicep:
    runs-on: ubuntu-latest
    environment:
      name: ${{ vars.env_name }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Install bicep
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicep
        sudo mv ./bicep /usr/local/bin/bicep
    - name: Build bicep
      run: bicep build main.bicep
    - name: Deploy bicep
      env:
        STEAMUSER: ${{ secrets.STEAMUSER }}
        STEAMPASS: ${{ secrets.STEAMPASS }}
      run: |
        rgName="cs-server-$env_name"
        az deployment group create \
          --resource-group "$rgName" \
          --template-file "infrastructure/azure/main.json" \
          --STEAMUSER "$STEAMUSER" \
          --STEAMPASS "$STEAMPASS" \
          --location "$location"
